services:
  postgres:
    image: postgres:latest
    container_name: postgres1
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - mynetwork

  web:
    build:
      context: .  # Refere-se ao Dockerfile na mesma pasta
    container_name: php_api
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    environment:
      DB_NAME: dbatividade1
      DB_USER: professor
      DB_PWD: professor
      DB_HOST: --- host -- 
      DB_PORT: 5432
      DB_TABLE: banco
    networks:
      - mynetwork
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin2
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "8081:80"
    networks:
      - mynetwork

volumes:
  postgres-data:

networks:
  mynetwork:

